typography_spectrum: 0.9170962700154632
color:
  brandStrength: 0.21666392125189304
  lightness: 0.6239177130628377
  saturation: 0.276381756644696
  rhythmicContrast: 0.07203933014534414
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.7154728313907981
author:
  name: Marvin Sharp
  email: marvin.sharp@memphis4.com
  url: www.memphis4.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d9a36cab-cbd5-478e-83c9-3adf1da16aad.png
name: Memphis4
title: Executing Performance Objectives
description: (and why you probably aren't doing it right)
